version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/3scale/3scale-go-client/
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            make test_coverage
            bash <(curl -s https://codecov.io/bash)
