version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/3scale/3scale-go-client/
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            make test_coverage
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
          when: always

      - run:
          name: Send coverage report to Code Climate
          command: |
            ./cc-test-reporter after-build -t gocov
          when: always